### ISSUE TITLE
can't save twitter consumer key ?

### ISSUE THREAD

**Issue by mtt2p** [skippednote/conversify#1]
look nice but i can't add the twitter consumer key and secret ? 
![bildschirmfoto 2014-01-13 um 21 19 05](https://f.cloud.github.com/assets/1998255/1904479/49694fca-7c90-11e3-8c9c-79d54315696b.png)
have to enter it manually ?

**Comment by skippednote** [comment]
Yes, you will have to create a twitter app and add in keys yourself.
